export const apiEndpoints = {
  dashboard: {
    kpi: '/dashboard/kpi',
    salesTrend: '/dashboard/sales-trend',
    topMenus: '/dashboard/top-menus',
    stockStatus: '/dashboard/stock-status',
    recentStockMovements: '/dashboard/recent-stock-movements',
  },
  auth: {
    login: '/auth/login',
    forgotPasswordRequestOtp: '/auth/forgot-password/request-otp',
    forgotPasswordVerifyOtp: '/auth/forgot-password/verify-otp',
    forgotPasswordResetPassword: '/auth/forgot-password/reset-password',
    logout: '/auth/logout',
  },
  user: {
    roles: '/user/roles',
    statuses: '/user/statuses',
    list: '/user',
    detail: (userId: string) => `/user/${userId}`,
    create: '/user',
    update: (userId: string) => `/user/${userId}`,
    remove: (userId: string) => `/user/${userId}`,
  },
  category: {
    options: '/category/options',
    list: '/category',
    detail: (categoryId: string) => `/category/${categoryId}`,
    create: '/category',
    update: (categoryId: string) => `/category/${categoryId}`,
    remove: (categoryId: string) => `/category/${categoryId}`,
  },
  unitMeasure: {
    options: '/unit-measure/options',
    list: '/unit-measure',
    detail: (unitMeasureId: string) => `/unit-measure/${unitMeasureId}`,
    create: '/unit-measure',
    update: (unitMeasureId: string) => `/unit-measure/${unitMeasureId}`,
    remove: (unitMeasureId: string) => `/unit-measure/${unitMeasureId}`,
  },
  ingredient: {
    options: '/ingredient/options',
    raw: {
      units: '/ingredient/raw/units',
      options: '/ingredient/raw/options',
      lowStock: '/ingredient/raw/low-stock',
      list: '/ingredient/raw',
      detail: (ingredientId: string) => `/ingredient/raw/${ingredientId}`,
      create: '/ingredient/raw',
      update: (ingredientId: string) => `/ingredient/raw/${ingredientId}`,
      remove: (ingredientId: string) => `/ingredient/raw/${ingredientId}`,
    },
    semi: {
      units: '/ingredient/semi/units',
      list: '/ingredient/semi',
      detail: (ingredientId: string) => `/ingredient/semi/${ingredientId}`,
      create: '/ingredient/semi',
      createAndProduce: '/ingredient/semi/create-and-produce',
      update: (ingredientId: string) => `/ingredient/semi/${ingredientId}`,
      remove: (ingredientId: string) => `/ingredient/semi/${ingredientId}`,
      hpp: (ingredientId: string) => `/ingredient/semi/${ingredientId}/hpp`,
      produce: (ingredientId: string) => `/ingredient/semi/${ingredientId}/produce`,
      recalculateHpp: (ingredientId: string) => `/ingredient/semi/${ingredientId}/recalculate-hpp`,
      composition: {
        availableIngredients: '/ingredient/semi/composition/available-ingredients',
        previewHpp: '/ingredient/semi/composition/preview-hpp',
        list: (ingredientId: string) => `/ingredient/semi/${ingredientId}/composition`,
        create: (ingredientId: string) => `/ingredient/semi/${ingredientId}/composition`,
        bulkReplace: (ingredientId: string) => `/ingredient/semi/${ingredientId}/composition/bulk`,
        update: (ingredientId: string, compositionId: string) => `/ingredient/semi/${ingredientId}/composition/${compositionId}`,
        remove: (ingredientId: string, compositionId: string) => `/ingredient/semi/${ingredientId}/composition/${compositionId}`,
      },
    },
  },
  menu: {
    list: '/menu',
    detail: (menuId: string) => `/menu/${menuId}`,
    create: '/menu',
    update: (menuId: string) => `/menu/${menuId}`,
    toggleAvailability: (menuId: string) => `/menu/${menuId}/toggle-availability`,
    remove: (menuId: string) => `/menu/${menuId}`,
    recipe: {
      list: (menuId: string) => `/menu/${menuId}/recipe`,
      create: (menuId: string) => `/menu/${menuId}/recipe`,
      bulkUpdate: (menuId: string) => `/menu/${menuId}/recipe`,
      update: (menuId: string, recipeId: string) => `/menu/${menuId}/recipe/${recipeId}`,
      remove: (menuId: string, recipeId: string) => `/menu/${menuId}/recipe/${recipeId}`,
    },
  },
  supplier: {
    list: '/supplier',
    detail: (supplierId: string) => `/supplier/${supplierId}`,
    create: '/supplier',
    update: (supplierId: string) => `/supplier/${supplierId}`,
    remove: (supplierId: string) => `/supplier/${supplierId}`,
  },
  inventory: {
    stockTypes: '/inventory/stock-types',
    stockIn: '/inventory/stock-in',
    stockOut: '/inventory/stock-out',
    ingredientHistory: (ingredientId: string) => `/inventory/ingredient/${ingredientId}`,
    list: '/inventory',
    detail: (stockMovementId: string) => `/inventory/${stockMovementId}`,
  },
  stockType: {
    list: '/stock-type',
    detail: (stockTypeId: string) => `/stock-type/${stockTypeId}`,
  },
  opname: {
    ingredients: '/opname/ingredients',
    list: '/opname',
    detail: (stockOpnameId: string) => `/opname/${stockOpnameId}`,
    create: '/opname',
    update: (stockOpnameId: string) => `/opname/${stockOpnameId}`,
    updateStatus: (stockOpnameId: string) => `/opname/${stockOpnameId}/status`,
    apply: (stockOpnameId: string) => `/opname/${stockOpnameId}/apply`,
    remove: (stockOpnameId: string) => `/opname/${stockOpnameId}`,
  },
  shift: {
    active: '/shift/active',
    my: '/shift/my',
    start: '/shift/start',
    end: '/shift/end',
    list: '/shift',
    detail: (shiftId: string) => `/shift/${shiftId}`,
    summary: (shiftId: string) => `/shift/${shiftId}/summary`,
  },
  cashMovement: {
    list: '/cash-movement',
    detail: (cashMovementId: string) => `/cash-movement/${cashMovementId}`,
    create: '/cash-movement',
  },
  order: {
    list: '/order',
    detail: (orderId: string) => `/order/${orderId}`,
    create: '/order',
    confirm: (orderId: string) => `/order/${orderId}/confirm`,
    cancel: (orderId: string) => `/order/${orderId}/cancel`,
    receipt: (orderId: string) => `/order/${orderId}/receipt`,
  },
  receipt: {
    pdf: (orderId: string) => `/receipt/${orderId}/pdf`,
    previewSample: '/receipt/preview-sample',
    preview: (orderId: string) => `/receipt/${orderId}/preview`,
    send: (orderId: string) => `/receipt/${orderId}/send`,
  },
  storeSetting: {
    publicInfo: '/store-setting/public/info',
    list: '/store-setting',
    map: '/store-setting/map',
    batchUpdate: '/store-setting/batch',
    detail: (settingKey: string) => `/store-setting/${settingKey}`,
    upsert: '/store-setting',
    update: (settingKey: string) => `/store-setting/${settingKey}`,
    remove: (settingKey: string) => `/store-setting/${settingKey}`,
  },
  upload: {
    image: (folder: 'menu' | 'logo') => `/upload/image/${folder}`,
    imageDefault: '/upload/image',
    removeImage: (folder: string, filename: string) => `/upload/image/${folder}/${filename}`,
    removeDefaultImage: (filename: string) => `/upload/image/${filename}`,
  },
  report: {
    financial: {
      full: '/report/financial',
      summary: '/report/financial/summary',
      payment: '/report/financial/payment',
      cashFlow: '/report/financial/cash-flow',
      topMenus: '/report/financial/top-menus',
      byCategory: '/report/financial/by-category',
    },
    inventory: {
      full: '/report/inventory',
      current: '/report/inventory/current',
      movement: '/report/inventory/movement',
      alerts: '/report/inventory/alerts',
      valuation: '/report/inventory/valuation',
      opname: '/report/inventory/opname',
      card: '/report/inventory/card',
    },
    operational: {
      full: '/report/operational',
      cashier: '/report/operational/cashier',
      shift: '/report/operational/shift',
      transactions: '/report/operational/transactions',
      menu: '/report/operational/menu',
      orderStatus: '/report/operational/order-status',
    },
    export: {
      pdf: '/report/export/pdf',
      excel: '/report/export/excel',
    },
  },
  spk: {
    analysis: '/spk/analysis',
  },
} as const
